### PR TITLE
Fix behavior of `Pages` in `@bibliography` blocks

### LINKED ISSUE #22: About non canonical bibliography inconsistencies (to autodocs)
(Sorry for posting yet another issue)

I noticed two interesting things about non canonical bibliographies, i.e. when I want to have a “Literature” section at the end of my documentation page.

assume the following: I have a source file called `src/functions/proximal_maps.jl` whose functions shall be documented on a page `/functions/proximal_maps.html` so I have a file `docs/src/functions/proximal_maps.md` to do that. This file could in a minimal sense look like in

````markdown
# [Proximal Maps](@id proximalMapFunctions)

```@autodocs
Modules = [Manopt]
Pages   = ["proximal_maps.jl"]
```

# Literature

```@bibliography
Pages = ["functions/proximal\_maps.md"]
Canonical=false
```
````

There is a few things to note

1. for `@autodocs` a file name is enough, while `@bibliography` needs the complete relative path
2. for `@autodocs` I do not have to escape the `_`, for `@bibliography` I do.
3. For `@bibliography` it would be nice to have a way to say (maybe something similarly short as the nice `*` “I want all references from this markdown file”, because this relative path to the markdown file I am in is currently something I type at several pages.

Besides these three points, the workflow overall is quite nice.

### PR DESCRIPTION
**Pull request by goerz**
The `Pages` field now behaves exactly as `Pages` in `@contents` and `@index` blocks: all files are relative to the directory containing the current file.

Also, by popular demand, `@__FILE__` is supported to refer to the current file (even though `@contents` and `@index` does not support this feature.

Closes #22

### CODE REVIEW

**Comment by goerz** [comment]
This is mostly internal changes, up to [a few new sentences in the documentation](https://juliadocs.org/DocumenterCitations.jl/previews/PR48/syntax/#noncanonical) that clarify the `Pages` field.

**Comment by goerz** [comment]
@kellertuer Can you have a look?

**Review by kellertuer — APPROVED** [review]
I can not evaluate the implementation itself, but the design and style looks good to me.

You write a bit skeptical here in the PR about the `@__FILE__` not being used in the other blocks. Well, the other ones also do not read their content from Markdown files so a self-reference is not happening there. :)

**Comment by goerz** [comment]
I got confused about `@autodocs`. I thought it was also taking `.md` files in its `Pages`, but it doesn't, so `@__FILE__` doesn't make sense there.

The `@content` and `@index` blocks *do* take `.md` files, though, no? Those seem like they have the same semantics for `Pages` as `@bibliography`, so I think https://github.com/JuliaDocs/Documenter.jl/issues/2301 and https://github.com/JuliaDocs/Documenter.jl/issues/2302 still apply, for consistency.

**Comment by goerz** [comment]
If there are no further comments, I will merge this sometime this weekend

**Pull request merged**
