### PR TITLE
Prevent duplicate labels in `:alpha` style

### LINKED ISSUE #26: Duplicate keys in `:alpha`betic style
Consider my (little lazy) example

```
@techreport{deCasteljau:1959,
    AUTHOR      = {de Casteljau, Paul},
    institution   = {Enveloppe Soleau 40.040, Institute National de la Propriété Industrielle, Paris.},
    TITLE       = {Outillage methodes calcul},
    YEAR        = {1959}
}
@techreport{deCasteljau:1959b,
    AUTHOR      = {de Casteljau, Paul},
    INSTITUTION = {Enveloppe Soleau 40.040, Institute National de la Propriété Industrielle, Paris.},
    TITLE       = {Outillage methodes calcul - my lazy b},
    YEAR        = {1959}
}
```

and a `temp.md`.

````
[deCasteljau:1959](@cite), [deCasteljau:1959b](@cite)
```@bibliography
Pages = ["temp.md"]
Canonical=false
```
````

Then the resulting page looks like

Screenshot 2023-07-17 at 17 04 05

So the generated _key_ clashes (considering them like hashes). They should at least be `[Cas59a]`, and `[Cas59b]` I think?

I might be mistaken, but I think the Keys would also respect the prefix of the name so that it would actually be `[dCa69]` – but maybe I remember that wrongly as well. The main part of this issue is the clash in keys, since this might also happen for other “Key collisions” I think (same author last names first letters in the same year for example).

PS: I promise this is the last issue for now, I even managed to rework my references and have a PR at https://manoptjl.org/previews/PR281/ that is (besides checking that non canonical bibliographies exist on all pages with references) reworked and I think it is overall quite nice! I just stumbled about this issue here by accident, so it does not appear in my references.

### PR DESCRIPTION
**Pull request by goerz**
This implements a stateful `AlphaStyle` that disambiguates the labels for the bibliography by appending a suffix "a", "b", etc. This emulates the behavior of the numeric citation style in LaTeX.

The existing `:alpha` style is automatically upgraded to the new `AlphaStyle`. It's a lot easier for users to pass `style=:alpha` than to instantiate the full `AlphaStyle`, in particular because `AlphaStyle` needs access to all the entries of the `.bib` file (so instantiating in manually would end up reading the `.bib` file twice). Moreover, there's no reason anyone would ever want to use the old "dumb" `:alpha` style.

In addition to the new `AlphaStyle`, this also fixes some inconsistencies relative to the alphabetic citation style in LaTeX:

* Up to four names are included in the label, not 3 (but 5 or more names results in 3 names and "+")
* The first letter of a "particle" of the name is included in the label, e.g. "vWB08" for a first author "von Winckel"

Closes #26

### CODE REVIEW

**Comment by goerz** [comment]
There's a preview at https://juliadocs.org/DocumenterCitations.jl/previews/PR31/gallery/#alphabetic_style

**Comment by goerz** [comment]
I'm going to mark this as "Draft" for now, since #29 convinced me that I'll probably want to tweak the arguments for the internal functions a little bit, and pass around the full `CitationBibliography` object (the instantiated plugin). The plugin object contains lots of state: all entries in the `.bib` file, all citations, which order they were cited in. The lack of access to this state in the various `format_*` routines already made `AlphaStyle` a little cumbersome, and implementing #29 or the most general version of #13 would likely be even more cumbersome.

So I'll probably make the changes to the internals and rebase this PR on top of that.

**Review by kellertuer — APPROVED** [review]

**Comment by goerz** [comment]
> https://github.com/JuliaDocs/DocumenterCitations.jl/issues/29 convinced me that I'll probably want to tweak the arguments for the internal functions a little bit, and pass around the full CitationBibliography object (the instantiated plugin).

It turns out there's a more elegant solution that doesn't require breaking backwards compatibility at all (not that the internal functions are part of the stable API; but I'd still rather not change them unless absolutely necessary):

I've added a new internal function `init_bibliography!(style, bib)` that is called at the beginning of the `ExpandBibliography` pipeline step. For the default `:numeric` style, this function does nothing, but for the revised `:alpha`/`AlphaStyle()`, this is where the unique keys for all entries in the `.bib` file are calculated and cached in an internal attribute of `AlphaStyle`.

It's a much cleaner implementation for the "smart" `:alpha` style than the previous iteration, and it also addresses #29.

This should now be ready for a final review and merge, and then I'll follow up with #32

**Review by kellertuer — APPROVED** [review]
Nice, this looks good to me, though I can not for a 100% review the internal code – the functionality seems to work very nicely.

**Comment by goerz** [comment]
@fredrikekre  Can I go ahead and merge, or did you want to further review this?

Also, since we didn't explicitly talk about this when QuantumCitations got merged back into DocumenterCitations and moved here: Should I still consider myself the primary maintainer of this project, as a direct continuation of QuantumCitations?

If yes, I would be a bit more direct in pushing the further development:

* I'll make general design decisions if they come up while dealing with PRs. I'll review and merge PRs.
* I'll organize tooling and CI mostly according to my needs and may push trivial and tooling-related commits directly to `master`
* I'll make any non-trivial changes via PRs and give people at least a week for review, but I'll ultimately merge my own PRs if there's no feedback. For any major changes or if I'm responding to feature requests, I'll actively solicit reviews/approval.
* I'll tag new releases and manage release notes, following semver.

None of this precludes any co-maintainers, i.e. you/anyone with push access to the repo from also doing any of those same things. In any case, especially with the transition to Documenter 1.0, I'll be coordinating with you and @mortenpi via comments here or on the `#Documentation` Slack channel.

**Comment by goerz** [comment]
If there are no further comments, I will merge this tomorrow

**Pull request merged**
