### PR TITLE
Set version to 1.0.0.

### PR DESCRIPTION
**Pull request by fredrikekre**
I think the package is ready to be released?

### CODE REVIEW

**Comment by goerz** [comment]
What do you think about https://github.com/JuliaDocs/DocumenterCitations.jl/issues/7#issuecomment-1631842855?

**Comment by goerz** [comment]
PR in #10, but if the idea of a warning isn't popular with everyone, this is definitely optional

**Comment by goerz** [comment]
Looks good to go! I've put today's date in `NEWS.md`. You are welcome to tag the registrator bot on this!

**Comment by fredrikekre** [comment]
Ah, I also made the same edit and force pushed after a rebase on master. If you didn't add anything else I think we are good to go.

Would you like to make a Discourse announcement? I didn't find this package announced there, and you have developed all of the new cool things.

**Comment by fredrikekre** [comment]
https://github.com/JuliaRegistries/General/pull/87368

**Comment by goerz** [comment]
Looks good, thanks! And Yes, I’ll draft an announcement for Discourse tonight. Good idea!

**Comment by goerz** [comment]
https://discourse.julialang.org/t/ann-documentercitations-v1-0-0/101562

**Pull request merged**
