### PR TITLE
Improve parsing of tex strings

### LINKED ISSUE #15: Curly braces in bibtex Fields
I just gave this a first try and noticed that my Zotero Export looks like

```
@book{Boumal:2023,
  title = {An {{Introduction}} to {{Optimization}} on {{Smooth Manifolds}}},
  author = {Boumal, Nicolas},
  year = {2023},
  month = mar,
  edition = {First},
  publisher = {{Cambridge University Press}},
  doi = {10.1017/9781009166164},
  isbn = {978-1-00-916616-4}
}
```

I am not sure why Zotero just gives curly braces to everyone, but probably it thinks it is necessary to preserve capitalisation.
Besides me also fighting how the keys will be rendered correctly the current literature then looks like

Screenshot 2023-07-13 at 11 31 30

So all curly braces are kept. In LaTeX these are not kept.
Sure this is also partly Zotero being stupid, but it would be great it curly braces could be removed here in the output

### PR DESCRIPTION
**Pull request by goerz**
Implements a proper (albeit limited) single-pass parser for the subset of tex syntax that occurs in BibTeX fields, converting to the equivalent Markdown. Most importantly, this handles [accents like `\"o`](https://www.bibtex.org/SpecialSymbols/), and groupings, i.e., it removes curly braces in the same way that LaTeX does.

Inline math is recognized and translated into Documenter's preferred "``" syntax, but otherwise is left alone.

A limited set of LaTeX commands is recognized, most notably `\href` and `\url`, allowing to put hyperlinks in the `@note` field of a reference. We're deliberately conservative here. Anyone who can demonstrate the need for additional commands should submit an issue with a real-life example. It should be quite trivial to add any specific additional command.

All of this is considered "very internal". We're not making any promises. Ideally, a lot of this code would probably be better off in Bibliography.jl, but at this point, we're treating Bibliography as just a basic parser to get the raw tex, and doing all the processing / conversion to Markdown ourselves.

Closes #15.

Should also address #44, ~except that the lack of a new `BibInternal` release still requires the workaround of using non-breaking spaces~.

### CODE REVIEW

**Comment by goerz** [comment]
The `\url`/`\href` support probably shouldn't be overused, but the rendering of links as in  [GoerzPhd2015](https://juliadocs.org/DocumenterCitations.jl/previews/PR52/references/#GoerzPhd2015) can be pretty neat, from the following `.bib` entry:

https://github.com/JuliaDocs/DocumenterCitations.jl/blob/8f83b487f45d693c0b8a63038da3235f8bbc48b0/docs/src/refs.bib#L278-L285

**Comment by goerz** [comment]
@kellertuer @Seelengrab @lgoettgens Can you have a look?

Are there any specific LaTeX commands that you would like me to add support for?

This should be the last PR that goes into the 1.3 release. It should also make `DocumenterCitations` pretty feature-complete, as far as I'm concerned. Thus, after the 1.3 release, I'd wait a while to see if anything comes up from the plugin being used in the wild, and then at some point release 1.4 that declares the documented Internals as "stable", as discussed in https://github.com/JuliaDocs/DocumenterCitations.jl/pull/43#issuecomment-1758667114.

**Comment by kellertuer** [comment]
I am fine with the current state of rendering I think.

**Comment by Seelengrab** [comment]
> Anyone who can demonstrate the need for additional commands should submit an issue with a real-life example. It should be quite trivial to add any specific additional command.

I was wondering whether supporting `urldate` would be ok? It's not technically bibtex if I'm not mistaken, but does give online ressources a better anchor.

Other than that, I'm very happy already with the current state, so nothing for me to add either :)

**Comment by goerz** [comment]
> I was wondering whether supporting urldate would be ok?

Can you open a separate issue for that, preferably with an example BibTeX entry, and how it should render?

**Comment by goerz** [comment]
@Seelengrab Opened #53, we can discuss `urldate` there.

**Pull request merged**
