### PR TITLE
Use tracefiles for coverage

### PR DESCRIPTION
**Pull request by goerz**
This is to avoid `.cov` files cluttering the src directory.

I'm opening this PR to test how it runs in the CI and whether the coverage information is correctly submitted to Codecov

### CODE REVIEW

**Comment by goerz** [comment]
For clarification: This uses a single `tracefile.info` when testing *locally* (via `make test` or by running `test()` in the development REPL). On CI, the more traditional `--code-coverage="user"` is still used, which produces `.cov` files in the `src` folder. I got the impression the `julia-actions/julia-processcoverage` works better with (only with?) `.cov` files. Also, we don't really care about "littering" on the CI system.

**Comment by IanButterworth** [comment]
I recommend not using `--code-coverage="user"` but instead use the `--code-coverage=@{path to repo}` because `user` tests all non-Base code, including stdlibs. `@` path approach will be much faster

**Comment by IanButterworth** [comment]
I forgot to mention it won't work on 1.6, so you may want to pass `user` or `@` in via a matrix or something

**Comment by goerz** [comment]
Yeah, I've been trying that, but Github apparently doesn't allow using `matrix` values either inside the `shell:` or `if:` values for a step.

**Comment by goerz** [comment]
Well, splitting it into two jobs (`test` and `testnocov`) does the trick.

I'm going to get rid of macOS testing, too. It fails (hangs) about 10% of the time, and it's really not necessary. First, I'm developing on macOS, so it's getting plenty of testing. Second, I've never seen something work on Linux and fail on macOS.

**Pull request merged**
