### PR TITLE
Render citations links as arbitrary markdown AST

### LINKED ISSUE #6: Multiple citations per link with "collapsed" rendering
I'd prefer to write [`Quantum optimal control [BrumerShapiro2003](@cite)[BrifNJP2010](@cite)[Shapiro2012](@cite)[KochJPCM2016](@cite)[SolaAAMOP2018](@cite)[MorzhinRMS2019](@cite)[Wilhelm2003.10132](@cite)[KochEPJQT2022](@cite)`](https://raw.githubusercontent.com/JuliaQuantumControl/QuantumControl.jl/3cb064f729e09d1479912b1074aeb4235426df3a/docs/src/index.md), which currently renders as "Quantum optimal control [[1]](https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/references/#BrumerShapiro2003)[[2]](https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/references/#BrifNJP2010)[[3]](https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/references/#Shapiro2012)[[4]](https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/references/#KochJPCM2016)[[5]](https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/references/#SolaAAMOP2018)[[6]](https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/references/#MorzhinRMS2019)[[7]](https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/references/#Wilhelm2003.10132)[[8]](https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/references/#KochEPJQT2022)", as the shorter 
`Quantum optimal control [BrumerShapiro2003, BrifNJP2010, Shapiro2012, KochJPCM2016, SolaAAMOP2018, MorzhinRMS2019, Wilhelm2003.10132, KochEPJQT2022](@cite)` and have it render as the collapsed "Quantum optimal control [[1](https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/references/#BrumerShapiro2003)-[8](https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/references/#KochEPJQT2022)]". Note that the rendered text has two separate links.

Parsing the citation syntax with multiple keys is already supported in the current `master` of DocumenterCitations:

```
julia> using DocumenterCitations: CitationLink

julia> using Markdown

julia> function _link(text::String)
           md = Markdown.parse(text)
           return md.content[1].content[1]
       end

julia> cit = CitationLink(_link("[BrumerShapiro2003, BrifNJP2010, Shapiro2012, KochJPCM2016, SolaAAMOP2018, MorzhinRMS2019, Wilhelm2003.10132, KochEPJQT2022](@cite)"))
CitationLink(
    link=Markdown.Link(Any["BrumerShapiro2003, BrifNJP2010, Shapiro2012, KochJPCM2016, SolaAAMOP2018, MorzhinRMS2019, Wilhelm2003.10132, KochEPJQT2022"], "@cite"),
    cmd=cite,
    style=nothing,
    keys=["BrumerShapiro2003", "BrifNJP2010", "Shapiro2012", "KochJPCM2016", "SolaAAMOP2018", "MorzhinRMS2019", "Wilhelm2003.10132", "KochEPJQT2022"],
    note=nothing,
    capitalize=false,
    starred=false,
    link_text=nothing
)
```

However, the feature is currently undocumented, since there is no (or at least no straightforward way) to *render* it with Documenter `0.27`: right now, the [`format_citation`](https://juliadocs.org/DocumenterCitations.jl/dev/internals/#DocumenterCitations.format_citation) function only modifies the *link text* of the citation link, but it doesn't break out of the structure of the single markdown link.

With the `master` version of Documenter, it should be possible to extend this: The `format_citation` for the above `CitationLink` should return an entire markdown snippet with multiple links, and that markdown snippet should then be parsed internally and inserted into the output tree.

How collapsed rendering would look with author-year styles is still to be determined. I'd mimic whatever RevTeX does as closely as possible.

### LINKED ISSUE #14: Support citation keys with underscores?
Congrats on the brand new release!
I just tried it with a bib file from https://zbib.org/, and I got a strange error due to a citation key with underscores `rabiner_tutorial_1989`:
```julia
┌ Error: Invalid bibtex key (nested markdown)
└ @ DocumenterCitations ~/.julia/packages/DocumenterCitations/ZXtrs/src/citations.jl:107
ERROR: Invalid citation: [rabiner*tutorial*1989](@cite)
```
Is it a Markdown thing or a DocumenterCitations thing?

### LINKED ISSUE #34: doctest and CitationBibliography
Consider the minimum example

```julia
using Documenter
using Documenter: doctest
using DocumenterCitations

doctest(Documenter)

# makedocs(
#    CitationBibliography(joinpath(@__DIR__, "bibliography.bib")),
#  ...
#
```

The returns the following error (but continues processing)
```
 Error: You are `using CitationBibligraphy`, but did not pass the plugin to `makedocs`
```

As far I can tell, there's no way to pass `CitationBibliography` to doctest. I am not sure what should be done in this case, but demoting the error to a warning seems like a good first step.

### LINKED ISSUE #41: Transform citations with missing references
Following up from https://github.com/JuliaDocs/DocumenterCitations.jl/issues/39#issuecomment-1724893008

If there are missing references (citations with no corresponding entries in a bibliography, e.g. due to a missing key in the `.bib` file), `makedocs` will show errors like this:

```
[ Info: ExpandCitations
┌ Warning: Bibliography anchor for key 'Mills2014b' not found.
└ @ DocumenterCitations ~/.julia/packages/DocumenterCitations/f0eDy/src/citations.jl:456
[ Info: CrossReferences: building cross-references.
┌ Error: invalid local link/image: file does not exist in src/PALEOcopse.md
│   link =
│    @ast MarkdownAST.Link("@cite", "") do
│      MarkdownAST.Text("Mills2014b")
│    end
│    
└ @ Documenter ~/.julia/packages/Documenter/nGNwI/src/utilities/utilities.jl:44
```

The second error is probably more confusing than helpful (and definitely redundant). It would be better if during the `ExpandCitations` step, citations without a corresponding bibliography entry would be transformed to something that's no longer a markdown link. That way, it wouldn't get picked up by the later `CrossReferences` step.

Maybe just keeping the "link text" in square brackets and making it red or something would do.

### PR DESCRIPTION
**Pull request by goerz**
This is a substantial rewrite of the internals handling the rendering of citation links. Before, a citation link (`[key](@cite)`, and all its variations) would stay a link, just with a different link text (as determined by `format_citation` for a particular `style`) and a different link target (an item in a bibliography block). Now, `format_citation` gets a `CitationLink` object (a parsed version of the original link) and returns a string with arbitrary markdown to replace the entire original link (not just the link text). Typically, the returned markdown will be something like `"[[1](@cite GoerzQ20222)]"`. That is, the replacement will contain another "direct" citation link, which is then rendered automatically with a single level of recursion.

The enhanced flexibility enables several new features and fixes existing bugs:

* We can have [multiple comma-separated citations](https://juliadocs.org/DocumenterCitations.jl/previews/PR43/syntax/#Syntax-for-Citations) in a single cite link. For the default `:numeric` style, these can be compressed ("Refs. [1–3]").
* We can handle missing references (in non-strict mode), showing question marks, just like LaTeX does it
* "Citation comments", like "Eq. (1)" in `[GoerzQ2022; Eq. (1)](@cite)` can now contain inline markdown (math, code, emphasis, etc.) that is preserved in the output
* We now support citation keys with underscores or anything else where the markdown parser was getting in the way.

The added complexity of the new approach was starting to turn the source code files a bit lengthy, so I've reorganized the code a little, collecting the implementation for the different built-in styles in the `styles` subfolder. This also allowed to remove some code duplication between the `:numeric` and `:alpha` styles. Internal functions that implement `format_citation` and `format_bibliography_reference` for the different builtin styles are now exposed in the documentation and simplify the implementation of custom styles. See [`NEWS.md`](https://github.com/JuliaDocs/DocumenterCitations.jl/blob/mg/collapsed-citations/NEWS.md) for more details about the change of the internals.

Closes #6
Closes #14
Closes #34
Closes #41

### CODE REVIEW

**Comment by goerz** [comment]
It might be worth revisiting what we define as the stable API of the `DocumenterCitations` package. If we take the narrow definition where everything mentioned on the "Internals" page is up for grabs, then the above changes are non-breaking. Specifically they are not breaking for anyone using `DocumenterCitations` using only the built-in styles.

However, the PR is *very* breaking for anyone who was using custom styles, including the [official example custom styles](https://juliadocs.org/DocumenterCitations.jl/stable/gallery/#custom_styles). I'd be open to an (even informal) policy of making a major version release if we break the internal routines that are documented for use with custom styles, as a courtesy. In general, I'd only change these routines if absolutely necessary, and the only other issue where I would foresee having to break compatibility again is #18.

I'd go with a majority opinion here, especially from those who have mentioned that they may be using custom styles (@lgoettgens, @kellertuer, @nathanaelbosch).

With the narrowest definition of the public API (which is the official one at the moment), the public API is really just the `DocumenterCitations` object itself and the syntax for the citation links and bibliography blocks: I don't see that we would ever break that, so this package would be a perpetual version 1.* (which is also fine by me).

**Comment by kellertuer** [comment]
I did not use a user defined style – and I see the two sides you are arguing – but maybe you are also “tricking” a bit with only exporting the object and hence declaring that the public API?

Maybe a way in between would be fair. With the current public API this PR is non-breaking.
You could still add a note to the news that it does break the internal structure that might have been used by some
You could further make the parts that users should use for their own styles part of the public API? That way users could more confidently use these parts of DocumenterCitations (and the next release that changes those would be breaking).

**Comment by goerz** [comment]
Preview is at https://juliadocs.org/DocumenterCitations.jl/previews/PR43/

See especially:

* [The syntax for multiple (combined) citations](https://juliadocs.org/DocumenterCitations.jl/previews/PR43/syntax/#Syntax-for-Citations)
* The [Gallery](https://juliadocs.org/DocumenterCitations.jl/previews/PR43/gallery/) on how this looks for the various built-in styles
* The newly exposed ["auxiliary customization routines"](https://juliadocs.org/DocumenterCitations.jl/previews/PR43/internals/#Auxiliary-customization-routines) (and the revised [Internals](https://juliadocs.org/DocumenterCitations.jl/previews/PR43/internals/) in general)
* The [simplified custom `:keylabels` style](https://juliadocs.org/DocumenterCitations.jl/previews/PR43/gallery/#Custom-style:-Citation-key-labels)

**Comment by goerz** [comment]
>  Maybe you are also “tricking” a bit with only exporting the object and hence declaring that the public API

Yeah, I'd definitely be okay with releasing this as `2.0`. and to label the "Internals" page as "this is stuff you only need to know if you want to contribute to the development of the package, or if you want to implement custom styles. It's not exported, but it's still part of the stable API".

The main counterargument would probably just be the general aversion against breaking releases. We only tagged 1.0 a couple of months ago, so it might be "too soon".

If we do decide to tag this at 2.0, then I'd like to think about the best way to implement #18 (which came up on Slack today) before making that release. There's different ways to approach #18, but at least one way would probably also involve a breaking change to the documented internals (the various `format_*` routine would have to know which `Writer` is rendering the documentation; more on that tomorrow). It's the only other breaking change of the internals that I can see on the horizon, so I think we might be pretty stable from 2.0 on out.

**Comment by kellertuer** [comment]
Oh, I was actually advocating to not release it as 2.0 ;)

But if you label this 1.3 – _and_ make the parts that users should use/modify public, __a next__ change like this would be (API-)breaking which gives users more confident in using things like the custom styling.

**Comment by lgoettgens** [comment]
I am very much in favor of declaring everything that is suggested in the docs to be used for custom styles as part of the API, i.e. this change would be considered breaking.

For my own projects with custom styles, however, this would be fine, if this PR gets released in the near future, as I didn't find the time to finally merge everything over there, yet. So I, personally, would be fine with the procedure described by @kellertuer.

**Comment by goerz** [comment]
Ok, that seems to be the consensus, then. We'll release this is at 1.3, but then declare the documented internal API as "stable" at some point in the near future – when I've made sure everything is in a state that I'm happy with for the foreseeable future. I'll make that official switch in its own release, so probably 1.4.

If there are no further comments, I'll merge this PR on Friday, and then work on #18, which will also make it into 1.3 (and is also slightly breaking)

**Pull request merged**
